name: Drift Detection and Retraining

on:
  push:
    branches:
      - main
      - master

jobs:
  detect_and_retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Drift Detection
        run: python drift_detection_script.py

      - name: Check Drift Status
        id: check_drift
        run: |
          echo "drift_detected=$(python -c "print('true' if '$(cat drift_detection_result.txt)' == 'Yes!' else 'false')")" >> $GITHUB_ENV
        # run: echo "::set-output name=drift_detected::$(python -c "print('true' if '$(cat drift_detection_result.txt)' == 'Yes!' else 'false')")"

      - name: Retrain Model (if drift detected)
        if: env.drift_detected == 'true'
        # steps.check_drift.outputs.drift_detected == 'true'
        run: python model.py

      - name: Commit Changes
        run: |
          git config --global user.email "asta.adelchi@gmail.com"
          git config --global user.name "adelchi91"
          # Check if there are changes before committing
          if [[ -n $(git diff --exit-code) ]]; then
            git add .
            git commit -m "Automated update due to drift detection"
            git push https://github.com/adelchi91/room_presence_detector.git
            # git push https://adelchi91:${{ secrets.GITHUB_TOKEN }}@github.com/adelchi91/room_presence_detector.git
          else
            echo "No changes detected. Skipping commit."
          fi


      - name: Build and Push Docker Image
        if: env.drift_detected == 'true'
        run: |
          docker build -t testing_image -f Dockerfile .
          docker tag testing_image adelchijacques/room_presence_classifier:room_presence_new
          docker login -u adelchijacques -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push adelchijacques/room_presence_classifier:room_presence_new